openapi: 3.0.0
info:
  title: {{project_name}} Yappa API
  version: {{project_version}}
paths:
  /{url+}:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: {{function_id}}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: url
          required: false
          style: simple