openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /{url+}:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ece60ceecftbmn56rj
        tag: $latest
      parameters:
        - description: Return ID
          explode: false
          in: path
          name: url
          required: false
          schema:
            type: string
          style: simple